# Generated by Django 2.2.2 on 2019-09-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('delete', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectivefromdate', models.DateTimeField()),
                ('effectivetodate', models.DateTimeField()),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxapp.Tax')),
            ],
        ),
    ]
