# Generated by Django 2.2.2 on 2019-07-27 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(db_column='c_id', primary_key=True, serialize=False)),
                ('client_name', models.CharField(db_column='c_name', max_length=255, unique=True)),
                ('is_active', models.SmallIntegerField(default=1, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(db_column='acc_id', primary_key=True, serialize=False)),
                ('account_name', models.CharField(db_column='acc_name', max_length=255, unique=True)),
                ('is_active', models.SmallIntegerField(default=1, max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catapp.Client')),
            ],
        ),
    ]
